using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;

namespace RoRModNET4
{
    internal class CharacterVars : MonoBehaviour
    {
        public float health = 250f;
        public string bodyName = "";
        public float baseSpeed = 0f;

        public Color[] colours = new Color[]
        {
            Color.white,
            Color.yellow,
            Color.blue,
            Color.red,
            Color.cyan,
            Color.green,
            Color.magenta,
            Color.black
        };

        public string[] pickupLines = new string[]
        {
            "Your juicy phat cock! <3",
            "A deadly disease",
            "Some dog shit I think?",
            "You.  He is carrying the crap out of this team.",
            "A small pigeon",
            "That sexy ass ;)",
            "Inconveniently oversized coconut"
        };

        public string[] bodyArray = new string[] {
            "AcidLarvaBody",
            "AffixEarthHealerBody",
            "AltarSkeletonBody",
            "AncientWispBody",
            "ArchWispBody",
            "ArtifactShellBody",
            "Assassin2Body",
            "AssassinBody",
            "BackupDroneBody",
            "BackupDroneOldBody",
            "Bandit2Body",
            "BanditBody",
            "BeetleBody",
            "BeetleCrystalBody",
            "BeetleGuardAllyBody",
            "BeetleGuardBody",
            "BeetleGuardCrystalBody",
            "BeetleQueen2Body",
            "BeetleWard",
            "BellBody",
            "BirdsharkBody",
            "BisonBody",
            "BomberBody",
            "BrotherBody",
            "BrotherGlassBody",
            "BrotherHauntBody",
            "BrotherHurtBody",
            "CaptainBody",
            "ClayBody",
            "ClayBossBody",
            "ClayBruiserBody",
            "ClayGrenadierBody",
            "CommandoBody",
            "CommandoPerformanceTestBody",
            "CrocoBody",
            "DeathProjectile",
            "Drone1Body",
            "Drone2Body",
            "DroneCommanderBody",
            "ElectricWormBody",
            "EmergencyDroneBody",
            "EnforcerBody",
            "EngiBeamTurretBody",
            "EngiBody",
            "EngiTurretBody",
            "EngiWalkerTurretBody",
            "EquipmentDroneBody",
            "ExplosivePotDestructibleBody",
            "FlameDroneBody",
            "FlyingVerminBody",
            "FusionCellDestructibleBody",
            "GeepBody",
            "GipBody",
            "GolemBody",
            "GolemBodyInvincible",
            "GrandParentBody",
            "GravekeeperBody",
            "GravekeeperTrackingFireball",
            "GreaterWispBody",
            "GupBody",
            "HANDBody",
            "HaulerBody",
            "HereticBody",
            "HermitCrabBody",
            "HuntressBody",
            "ImpBody",
            "ImpBossBody",
            "JellyfishBody",
            "LemurianBody",
            "LemurianBruiserBody",
            "LoaderBody",
            "LunarExploderBody",
            "LunarGolemBody",
            "LunarWispBody",
            "LunarWispTrackingBomb",
            "MageBody",
            "MagmaWormBody",
            "MajorConstructBody",
            "MegaConstructBody",
            "MegaDroneBody",
            "MercBody",
            "MiniMushroomBody",
            "MiniVoidRaidCrabBodyBase",
            "MiniVoidRaidCrabBodyPhase1",
            "MiniVoidRaidCrabBodyPhase2",
            "MiniVoidRaidCrabBodyPhase3",
            "MinorConstructAttachableBody",
            "MinorConstructBody",
            "MinorConstructOnKillBody",
            "MissileDroneBody",
            "NullifierAllyBody",
            "NullifierBody",
            "PaladinBody",
            "ParentBody",
            "ParentPodBody",
            "Pot2Body",
            "PotMobile2Body",
            "PotMobileBody",
            "RailgunnerBody",
            "RoboBallBossBody",
            "RoboBallGreenBuddyBody",
            "RoboBallMiniBody",
            "RoboBallRedBuddyBody",
            "SMInfiniteTowerMaulingRockLarge",
            "SMInfiniteTowerMaulingRockMedium",
            "SMInfiniteTowerMaulingRockSmall",
            "SMMaulingRockLarge",
            "SMMaulingRockMedium",
            "SMMaulingRockSmall",
            "ScavBody",
            "ScavLunar1Body",
            "ScavLunar2Body",
            "ScavLunar3Body",
            "ScavLunar4Body",
            "ScavSackProjectile",
            "ShopkeeperBody",
            "SniperBody",
            "SpectatorBody",
            "SpectatorSlowBody",
            "SquidTurretBody",
            "SulfurPodBody",
            "SuperRoboBallBossBody",
            "TimeCrystalBody",
            "TitanBody",
            "TitanGoldBody",
            "ToolbotBody",
            "TreebotBody",
            "Turret1Body",
            "UrchinTurretBody",
            "VagrantBody",
            "VagrantTrackingBomb",
            "VerminBody",
            "VoidBarnacleBody",
            "VoidBarnacleNoCastBody",
            "VoidInfestorBody",
            "VoidJailerAllyBody",
            "VoidJailerBody",
            "VoidMegaCrabAllyBody",
            "VoidMegaCrabBody",
            "VoidRaidCrabBody",
            "VoidRaidCrabJointBody",
            "VoidSurvivorBody",
            "VultureBody",
            "VultureEggBody",
            "WispBody",
            "WispSoulBody"
        };
    }
}
